import type {
  ProfessionId,
  ProfessionConfig,
  ProfessionTerminology,
  NavItem,
  KPIDefinition,
  DashboardWidget,
  PipelineStage,
  DefaultWorkflow,
} from './types'

const defaultTerminology: ProfessionTerminology = {
  customer: 'Customer',
  customerPlural: 'Customers',
  appointment: 'Appointment',
  appointmentPlural: 'Appointments',
  project: 'Project',
  projectPlural: 'Projects',
  invoice: 'Invoice',
  invoicePlural: 'Invoices',
  quote: 'Quote',
  quotePlural: 'Quotes',
  product: 'Product',
  productPlural: 'Products',
  deal: 'Deal',
  dealPlural: 'Deals',
  revenue: 'Revenue',
  note: 'Note',
  notePlural: 'Notes',
  task: 'Task',
  taskPlural: 'Tasks',
  file: 'File',
  filePlural: 'Files',
  followUp: 'Follow-up',
  consultation: 'Consultation',
  proposal: 'Proposal',
  payment: 'Payment',
  paymentPlural: 'Payments',
  staff: 'Staff',
  staffPlural: 'Staff',
  service: 'Service',
  servicePlural: 'Services',
}

const professionConfigs: Record<ProfessionId, ProfessionConfig> = {
  realtor: {
    id: 'realtor',
    name: 'Real Estate',
    description: 'Real estate agents and brokers',
    icon: 'Home',
    color: '#059669',
    terminology: {
      ...defaultTerminology,
      customer: 'Contact',
      customerPlural: 'Contacts',
      appointment: 'Property Viewing',
      appointmentPlural: 'Property Viewings',
      project: 'Transaction',
      projectPlural: 'Transactions',
      invoice: 'Commission Statement',
      invoicePlural: 'Commission Statements',
      quote: 'Offer',
      quotePlural: 'Offers',
      product: 'Property',
      productPlural: 'Properties',
      deal: 'Deal',
      dealPlural: 'Deals',
      revenue: 'Commission',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Activity',
      taskPlural: 'Activities',
      file: 'Document',
      filePlural: 'Documents',
      followUp: 'Follow-up',
      consultation: 'Property Consultation',
      proposal: 'Offer',
      payment: 'Commission',
      paymentPlural: 'Commissions',
      staff: 'Agent',
      staffPlural: 'Agents',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Command Center', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Contacts', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'properties', label: 'Properties', icon: 'Building2', href: '/dashboard/contacts', priority: 3, group: 'primary' },
      { id: 'appointments', label: 'Viewings', icon: 'Calendar', href: '/appointments', priority: 4, group: 'primary' },
      { id: 'opportunities', label: 'Pipeline', icon: 'TrendingUp', href: '/dashboard/opportunities', priority: 5, group: 'primary' },
      { id: 'invoices', label: 'Commissions', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'tasks', label: 'Activities', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 7, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 8, group: 'tools' },
      { id: 'teams', label: 'Agents', icon: 'Users', href: '/dashboard/teams', priority: 9, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 10, group: 'tools' },
    ],
    kpis: [
      { id: 'active_listings', label: 'Active Listings', icon: 'Building2', format: 'number', description: 'Properties currently listed', query: 'active_listings' },
      { id: 'viewings_this_week', label: 'Viewings This Week', icon: 'Calendar', format: 'number', description: 'Scheduled property viewings', query: 'viewings_this_week' },
      { id: 'open_offers', label: 'Open Offers', icon: 'FileText', format: 'number', description: 'Pending offers to review', query: 'open_offers' },
      { id: 'commission_pending', label: 'Pending Commission', icon: 'DollarSign', format: 'currency', description: 'Commission awaiting closure', query: 'commission_pending' },
      { id: 'contacts_added', label: 'New Contacts', icon: 'UserPlus', format: 'number', description: 'Contacts added this month', query: 'contacts_added' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Business Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Business Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_viewings', label: "Today's Viewings", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Deal Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_viewings', label: 'Upcoming Viewings', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'recent_contacts', label: 'Recent Contacts', type: 'list', size: 'md', priority: 6, query: 'recent_contacts' },
      { id: 'revenue', label: 'Commission Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'inquiry', label: 'New Inquiry', color: '#3b82f6', probability: 10 },
      { id: 'consultation', label: 'Consultation', color: '#8b5cf6', probability: 25 },
      { id: 'viewing', label: 'Property Viewing', color: '#06b6d4', probability: 40 },
      { id: 'offer', label: 'Offer Made', color: '#f59e0b', probability: 60 },
      { id: 'negotiation', label: 'Negotiation', color: '#f97316', probability: 75 },
      { id: 'closing', label: 'Closing', color: '#10b981', probability: 90 },
      { id: 'won', label: 'Closed Won', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Closed Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Viewing Confirmation', description: 'Send confirmation when a property viewing is booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Property Viewing Confirmation - {{property_address}}', message: 'Dear {{customer_name}},\n\nThis confirms your property viewing scheduled for {{appointment_date}} at {{appointment_time}}.\n\nPlease let us know if you need to reschedule.\n\nBest regards,\n{{business_name}}' },
      { name: 'Post-Viewing Follow-up', description: 'Follow up 24 hours after a viewing', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'Thank you for viewing - {{property_address}}', message: 'Dear {{customer_name}},\n\nThank you for taking the time to view {{property_address}} yesterday. We would love to hear your thoughts.\n\nPlease don\'t hesitate to reach out with any questions.\n\nBest regards,\n{{business_name}}' },
      { name: 'New Lead Notification', description: 'Notify team when a new lead books a viewing', trigger: 'booking_confirmed', actionType: 'internal_notification', message: 'New lead: {{customer_name}} has booked a property viewing for {{appointment_date}}.' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'invoices', 'tasks', 'workflows', 'teams'],
    hiddenModules: [],
  },

  doctor: {
    id: 'doctor',
    name: 'Healthcare',
    description: 'Doctors, clinics, and healthcare providers',
    icon: 'Stethoscope',
    color: '#dc2626',
    terminology: {
      ...defaultTerminology,
      customer: 'Patient',
      customerPlural: 'Patients',
      appointment: 'Consultation',
      appointmentPlural: 'Consultations',
      project: 'Treatment Plan',
      projectPlural: 'Treatment Plans',
      invoice: 'Consultation Fee',
      invoicePlural: 'Consultation Fees',
      quote: 'Estimate',
      quotePlural: 'Estimates',
      product: 'Service',
      productPlural: 'Services',
      deal: 'Case',
      dealPlural: 'Cases',
      revenue: 'Revenue',
      note: 'Medical Note',
      notePlural: 'Medical Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'Record',
      filePlural: 'Records',
      followUp: 'Review Visit',
      consultation: 'Consultation',
      proposal: 'Treatment Plan',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Doctor',
      staffPlural: 'Doctors',
      service: 'Medical Service',
      servicePlural: 'Medical Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Practice Hub', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Patients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Consultations', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 4, group: 'primary' },
      { id: 'invoices', label: 'Fees & Payments', icon: 'DollarSign', href: '/dashboard/invoices', priority: 5, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 6, group: 'tools' },
      { id: 'teams', label: 'Staff', icon: 'Users', href: '/dashboard/teams', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'patients_today', label: 'Patients Today', icon: 'Users', format: 'number', description: 'Consultations scheduled today', query: 'today_appointments' },
      { id: 'pending_reviews', label: 'Pending Reviews', icon: 'ClipboardList', format: 'number', description: 'Patients requiring follow-up', query: 'pending_followups' },
      { id: 'revenue_this_month', label: 'Revenue This Month', icon: 'DollarSign', format: 'currency', description: 'Consultation fees collected', query: 'revenue_month' },
      { id: 'no_shows', label: 'No-shows', icon: 'UserX', format: 'number', description: 'Missed appointments this month', query: 'no_shows_month' },
      { id: 'total_patients', label: 'Total Patients', icon: 'Heart', format: 'number', description: 'Unique patients seen', query: 'total_contacts' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Practice Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Practice Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_consultations', label: "Today's Consultations", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'upcoming_consultations', label: 'Upcoming Consultations', type: 'list', size: 'lg', priority: 4, query: 'upcoming_appointments' },
      { id: 'recent_patients', label: 'Recent Patients', type: 'list', size: 'md', priority: 5, query: 'recent_contacts' },
      { id: 'pending_followups', label: 'Follow-ups Required', type: 'list', size: 'md', priority: 6, query: 'pending_followups' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'new_patient', label: 'New Patient', color: '#3b82f6', probability: 20 },
      { id: 'initial_consultation', label: 'Initial Consultation', color: '#8b5cf6', probability: 40 },
      { id: 'treatment_plan', label: 'Treatment Plan', color: '#06b6d4', probability: 60 },
      { id: 'in_treatment', label: 'In Treatment', color: '#f59e0b', probability: 75 },
      { id: 'follow_up', label: 'Follow-up Required', color: '#f97316', probability: 85 },
      { id: 'completed', label: 'Treatment Complete', color: '#22c55e', probability: 100 },
    ],
    defaultWorkflows: [
      { name: 'Appointment Confirmation', description: 'Confirm consultations when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Consultation Confirmation', message: 'Dear {{customer_name}},\n\nThis confirms your consultation scheduled for {{appointment_date}} at {{appointment_time}}.\n\nPlease arrive 10 minutes early to complete any necessary paperwork.\n\nBest regards,\n{{business_name}}' },
      { name: 'Post-Consultation Follow-up', description: 'Schedule follow-up after consultation', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'Follow-up Reminder', message: 'Dear {{customer_name}},\n\nThank you for your consultation yesterday. If you have any questions about your treatment plan, please don\'t hesitate to contact us.\n\nBest regards,\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: ['opportunities'],
  },

  lawyer: {
    id: 'lawyer',
    name: 'Legal',
    description: 'Lawyers, attorneys, and legal practices',
    icon: 'Scale',
    color: '#7c3aed',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Consultation',
      appointmentPlural: 'Consultations',
      project: 'Case',
      projectPlural: 'Cases',
      invoice: 'Legal Invoice',
      invoicePlural: 'Legal Invoices',
      quote: 'Fee Estimate',
      quotePlural: 'Fee Estimates',
      product: 'Service',
      productPlural: 'Services',
      deal: 'Matter',
      dealPlural: 'Matters',
      revenue: 'Billing',
      note: 'Case Note',
      notePlural: 'Case Notes',
      task: 'Case Activity',
      taskPlural: 'Case Activities',
      file: 'Legal Document',
      filePlural: 'Legal Documents',
      followUp: 'Follow-up',
      consultation: 'Legal Consultation',
      proposal: 'Fee Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Attorney',
      staffPlural: 'Attorneys',
      service: 'Legal Service',
      servicePlural: 'Legal Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Case Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'opportunities', label: 'Active Matters', icon: 'Briefcase', href: '/dashboard/opportunities', priority: 3, group: 'primary' },
      { id: 'appointments', label: 'Consultations', icon: 'Calendar', href: '/appointments', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Case Activities', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Billing', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'teams', label: 'Attorneys', icon: 'Users', href: '/dashboard/teams', priority: 8, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 9, group: 'tools' },
    ],
    kpis: [
      { id: 'active_cases', label: 'Active Cases', icon: 'Briefcase', format: 'number', description: 'Open legal matters', query: 'active_opportunities' },
      { id: 'consultations_week', label: 'Consultations This Week', icon: 'Calendar', format: 'number', description: 'Client consultations scheduled', query: 'viewings_this_week' },
      { id: 'outstanding_billing', label: 'Outstanding Billing', icon: 'DollarSign', format: 'currency', description: 'Unpaid invoices total', query: 'outstanding_invoices' },
      { id: 'pending_activities', label: 'Pending Activities', icon: 'Clock', format: 'number', description: 'Case activities due', query: 'pending_tasks' },
      { id: 'total_clients', label: 'Total Clients', icon: 'Users', format: 'number', description: 'Active client base', query: 'total_contacts' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Legal Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Practice Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_consultations', label: "Today's Consultations", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'active_matters', label: 'Active Matters', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_consultations', label: 'Upcoming Consultations', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'pending_activities', label: 'Pending Activities', type: 'list', size: 'md', priority: 6, query: 'pending_tasks' },
      { id: 'billing', label: 'Billing Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'intake', label: 'Initial Intake', color: '#3b82f6', probability: 15 },
      { id: 'consultation', label: 'Consultation', color: '#8b5cf6', probability: 30 },
      { id: 'engagement', label: 'Engagement Letter', color: '#06b6d4', probability: 50 },
      { id: 'active', label: 'Active Case', color: '#f59e0b', probability: 70 },
      { id: 'settlement', label: 'Settlement/Negotiation', color: '#f97316', probability: 85 },
      { id: 'closed_won', label: 'Case Won/Settled', color: '#22c55e', probability: 100 },
      { id: 'closed_lost', label: 'Case Lost/Dismissed', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Consultation Confirmation', description: 'Confirm consultations when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Legal Consultation Confirmation', message: 'Dear {{customer_name}},\n\nThis confirms your legal consultation scheduled for {{appointment_date}} at {{appointment_time}}.\n\nPlease bring any relevant documents to your consultation.\n\nBest regards,\n{{business_name}}' },
      { name: 'Post-Consultation Follow-up', description: 'Follow up after initial consultation', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'Follow-up - Your Legal Consultation', message: 'Dear {{customer_name}},\n\nThank you for meeting with us. Based on our discussion, please find attached the next steps for your matter.\n\nBest regards,\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: [],
  },

  freelancer: {
    id: 'freelancer',
    name: 'Freelance',
    description: 'Freelancers and independent contractors',
    icon: 'Laptop',
    color: '#2563eb',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Meeting',
      appointmentPlural: 'Meetings',
      project: 'Contract',
      projectPlural: 'Contracts',
      invoice: 'Client Invoice',
      invoicePlural: 'Client Invoices',
      quote: 'Proposal',
      quotePlural: 'Proposals',
      product: 'Service',
      productPlural: 'Services',
      deal: 'Opportunity',
      dealPlural: 'Opportunities',
      revenue: 'Income',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Deliverable',
      taskPlural: 'Deliverables',
      file: 'File',
      filePlural: 'Files',
      followUp: 'Follow-up',
      consultation: 'Discovery Call',
      proposal: 'Project Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Collaborator',
      staffPlural: 'Collaborators',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Workspace', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Meetings', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'opportunities', label: 'Pipeline', icon: 'TrendingUp', href: '/dashboard/opportunities', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Deliverables', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'active_contracts', label: 'Active Contracts', icon: 'FileText', format: 'number', description: 'Ongoing client contracts', query: 'active_opportunities' },
      { id: 'meetings_week', label: 'Meetings This Week', icon: 'Calendar', format: 'number', description: 'Client meetings scheduled', query: 'viewings_this_week' },
      { id: 'pending_proposals', label: 'Pending Proposals', icon: 'Send', format: 'number', description: 'Awaiting client response', query: 'open_offers' },
      { id: 'income_month', label: 'Income This Month', icon: 'DollarSign', format: 'currency', description: 'Revenue received', query: 'revenue_month' },
      { id: 'outstanding', label: 'Outstanding Invoices', icon: 'AlertCircle', format: 'currency', description: 'Unpaid invoices', query: 'outstanding_invoices' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Business Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Business Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_meetings', label: "Today's Meetings", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Client Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_meetings', label: 'Upcoming Meetings', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'recent_clients', label: 'Recent Clients', type: 'list', size: 'md', priority: 6, query: 'recent_contacts' },
      { id: 'revenue', label: 'Income Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'lead', label: 'New Lead', color: '#3b82f6', probability: 10 },
      { id: 'discovery', label: 'Discovery Call', color: '#8b5cf6', probability: 25 },
      { id: 'proposal', label: 'Proposal Sent', color: '#06b6d4', probability: 45 },
      { id: 'negotiation', label: 'Negotiation', color: '#f59e0b', probability: 65 },
      { id: 'contract', label: 'Contract Signed', color: '#f97316', probability: 85 },
      { id: 'won', label: 'Project Won', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Meeting Confirmation', description: 'Confirm client meetings when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Meeting Confirmation - {{business_name}}', message: 'Hi {{customer_name}},\n\nJust confirming our meeting on {{appointment_date}} at {{appointment_time}}.\n\nLooking forward to it!\n\nBest,\n{{business_name}}' },
      { name: 'Post-Meeting Follow-up', description: 'Follow up after client meeting', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'Great meeting today!', message: 'Hi {{customer_name}},\n\nThanks for the great meeting today! As discussed, I\'ll get started on the next steps.\n\nTalk soon,\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows'],
    hiddenModules: ['teams'],
  },

  consultant: {
    id: 'consultant',
    name: 'Consulting',
    description: 'Business consultants and advisors',
    icon: 'Briefcase',
    color: '#0891b2',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Meeting',
      appointmentPlural: 'Meetings',
      project: 'Engagement',
      projectPlural: 'Engagements',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Proposal',
      quotePlural: 'Proposals',
      product: 'Service',
      productPlural: 'Services',
      deal: 'Opportunity',
      dealPlural: 'Opportunities',
      revenue: 'Revenue',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Action Item',
      taskPlural: 'Action Items',
      file: 'Document',
      filePlural: 'Documents',
      followUp: 'Follow-up',
      consultation: 'Discovery Session',
      proposal: 'Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Consultant',
      staffPlural: 'Consultants',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Command Center', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'opportunities', label: 'Pipeline', icon: 'TrendingUp', href: '/dashboard/opportunities', priority: 3, group: 'primary' },
      { id: 'appointments', label: 'Meetings', icon: 'Calendar', href: '/appointments', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Action Items', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'teams', label: 'Consultants', icon: 'Users', href: '/dashboard/teams', priority: 8, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 9, group: 'tools' },
    ],
    kpis: [
      { id: 'active_engagements', label: 'Active Engagements', icon: 'Briefcase', format: 'number', description: 'Ongoing client engagements', query: 'active_opportunities' },
      { id: 'meetings_week', label: 'Meetings This Week', icon: 'Calendar', format: 'number', description: 'Client meetings scheduled', query: 'viewings_this_week' },
      { id: 'open_proposals', label: 'Open Proposals', icon: 'FileText', format: 'number', description: 'Awaiting client decision', query: 'open_offers' },
      { id: 'revenue_month', label: 'Revenue This Month', icon: 'DollarSign', format: 'currency', description: 'Consulting revenue', query: 'revenue_month' },
      { id: 'pipeline_value', label: 'Pipeline Value', icon: 'TrendingUp', format: 'currency', description: 'Total pipeline value', query: 'pipeline_value' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Business Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Business Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_meetings', label: "Today's Meetings", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Engagement Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_meetings', label: 'Upcoming Meetings', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'action_items', label: 'Pending Action Items', type: 'list', size: 'md', priority: 6, query: 'pending_tasks' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'lead', label: 'New Lead', color: '#3b82f6', probability: 10 },
      { id: 'discovery', label: 'Discovery Session', color: '#8b5cf6', probability: 30 },
      { id: 'proposal', label: 'Proposal Sent', color: '#06b6d4', probability: 50 },
      { id: 'negotiation', label: 'Negotiation', color: '#f59e0b', probability: 70 },
      { id: 'signed', label: 'Engagement Signed', color: '#f97316', probability: 85 },
      { id: 'won', label: 'Engagement Won', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Meeting Confirmation', description: 'Confirm client meetings when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Meeting Confirmation', message: 'Hi {{customer_name}},\n\nThis confirms our meeting on {{appointment_date}} at {{appointment_time}}.\n\nSee you then!\n\nBest regards,\n{{business_name}}' },
      { name: 'Post-Meeting Follow-up', description: 'Follow up after consulting meeting', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'Meeting Summary & Next Steps', message: 'Hi {{customer_name}},\n\nThank you for the productive meeting. As discussed, here are the next steps:\n\nPlease don\'t hesitate to reach out with questions.\n\nBest regards,\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: [],
  },

  salon: {
    id: 'salon',
    name: 'Salon & Beauty',
    description: 'Hair salons, nail studios, and beauty businesses',
    icon: 'Scissors',
    color: '#db2777',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Booking',
      appointmentPlural: 'Bookings',
      project: 'Service Package',
      projectPlural: 'Service Packages',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Quote',
      quotePlural: 'Quotes',
      product: 'Retail Product',
      productPlural: 'Retail Products',
      deal: 'Package',
      dealPlural: 'Packages',
      revenue: 'Revenue',
      note: 'Style Note',
      notePlural: 'Style Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'File',
      filePlural: 'Files',
      followUp: 'Rebook Reminder',
      consultation: 'Consultation',
      proposal: 'Quote',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Stylist',
      staffPlural: 'Stylists',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Salon Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Bookings', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 4, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 5, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 6, group: 'tools' },
      { id: 'teams', label: 'Stylists', icon: 'Users', href: '/dashboard/teams', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'bookings_today', label: "Today's Bookings", icon: 'Calendar', format: 'number', description: 'Appointments today', query: 'today_appointments' },
      { id: 'rebook_rate', label: 'Rebook Rate', icon: 'Repeat', format: 'percentage', description: 'Clients who rebooked', query: 'rebook_rate' },
      { id: 'revenue_day', label: "Today's Revenue", icon: 'DollarSign', format: 'currency', description: 'Revenue earned today', query: 'revenue_day' },
      { id: 'new_clients_month', label: 'New Clients', icon: 'UserPlus', format: 'number', description: 'New clients this month', query: 'contacts_added' },
      { id: 'no_shows', label: 'No-shows', icon: 'UserX', format: 'number', description: 'Missed bookings this month', query: 'no_shows_month' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Salon Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Salon Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_bookings', label: "Today's Bookings", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'upcoming_bookings', label: 'Upcoming Bookings', type: 'list', size: 'lg', priority: 4, query: 'upcoming_appointments' },
      { id: 'recent_clients', label: 'Recent Clients', type: 'list', size: 'md', priority: 5, query: 'recent_contacts' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 6, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 7, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'inquiry', label: 'New Inquiry', color: '#3b82f6', probability: 15 },
      { id: 'booked', label: 'First Booking', color: '#8b5cf6', probability: 40 },
      { id: 'visited', label: 'Visited', color: '#06b6d4', probability: 60 },
      { id: 'regular', label: 'Regular Client', color: '#f59e0b', probability: 80 },
      { id: 'vip', label: 'VIP Client', color: '#22c55e', probability: 100 },
    ],
    defaultWorkflows: [
      { name: 'Booking Confirmation', description: 'Confirm bookings when made', trigger: 'booking_confirmed', actionType: 'email', subject: 'Booking Confirmation - {{business_name}}', message: 'Hi {{customer_name}},\n\nYour booking is confirmed for {{appointment_date}} at {{appointment_time}}.\n\nWe look forward to seeing you!\n\n{{business_name}}' },
      { name: 'Rebook Reminder', description: 'Remind clients to rebook after 4 weeks', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 40320, subject: 'Time for your next visit!', message: 'Hi {{customer_name}},\n\nIt\'s been a while since your last visit! We\'d love to see you again.\n\nBook your next appointment today.\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: ['opportunities'],
  },

  gym: {
    id: 'gym',
    name: 'Gym & Fitness',
    description: 'Gyms, personal trainers, and fitness studios',
    icon: 'Dumbbell',
    color: '#ea580c',
    terminology: {
      ...defaultTerminology,
      customer: 'Member',
      customerPlural: 'Members',
      appointment: 'Session',
      appointmentPlural: 'Sessions',
      project: 'Program',
      projectPlural: 'Programs',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Quote',
      quotePlural: 'Quotes',
      product: 'Membership',
      productPlural: 'Memberships',
      deal: 'Enrollment',
      dealPlural: 'Enrollments',
      revenue: 'Revenue',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'File',
      filePlural: 'Files',
      followUp: 'Check-in',
      consultation: 'Assessment',
      proposal: 'Program Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Trainer',
      staffPlural: 'Trainers',
      service: 'Class',
      servicePlural: 'Classes',
    },
    navItems: [
      { id: 'dashboard', label: 'Gym Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Members', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Sessions', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 4, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 5, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 6, group: 'tools' },
      { id: 'teams', label: 'Trainers', icon: 'Users', href: '/dashboard/teams', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'sessions_today', label: 'Sessions Today', icon: 'Calendar', format: 'number', description: 'Training sessions today', query: 'today_appointments' },
      { id: 'active_members', label: 'Active Members', icon: 'Users', format: 'number', description: 'Currently active members', query: 'total_contacts' },
      { id: 'new_signups', label: 'New Sign-ups', icon: 'UserPlus', format: 'number', description: 'New members this month', query: 'contacts_added' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'retention_rate', label: 'Retention Rate', icon: 'Heart', format: 'percentage', description: 'Member retention rate', query: 'rebook_rate' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Fitness Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Gym Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_sessions', label: "Today's Sessions", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'upcoming_sessions', label: 'Upcoming Sessions', type: 'list', size: 'lg', priority: 4, query: 'upcoming_appointments' },
      { id: 'recent_members', label: 'Recent Members', type: 'list', size: 'md', priority: 5, query: 'recent_contacts' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 6, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 7, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'lead', label: 'Lead', color: '#3b82f6', probability: 15 },
      { id: 'trial', label: 'Trial Session', color: '#8b5cf6', probability: 35 },
      { id: 'consultation', label: 'Fitness Assessment', color: '#06b6d4', probability: 55 },
      { id: 'enrolled', label: 'Enrolled', color: '#f59e0b', probability: 80 },
      { id: 'active', label: 'Active Member', color: '#22c55e', probability: 100 },
      { id: 'churned', label: 'Churned', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Session Confirmation', description: 'Confirm training sessions when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Session Confirmation', message: 'Hi {{customer_name}},\n\nYour training session is confirmed for {{appointment_date}} at {{appointment_time}}.\n\nSee you at the gym!\n\n{{business_name}}' },
      { name: 'Check-in After Session', description: 'Check in with members after sessions', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'Great workout today!', message: 'Hi {{customer_name}},\n\nGreat session today! Keep up the momentum.\n\nYour next session is coming up. Let us know if you need anything.\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: ['opportunities'],
  },

  contractor: {
    id: 'contractor',
    name: 'Contractor',
    description: 'General contractors, painters, plumbers, and tradespeople',
    icon: 'Hammer',
    color: '#ca8a04',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Site Visit',
      appointmentPlural: 'Site Visits',
      project: 'Project',
      projectPlural: 'Projects',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Estimate',
      quotePlural: 'Estimates',
      product: 'Material',
      productPlural: 'Materials',
      deal: 'Project',
      dealPlural: 'Projects',
      revenue: 'Revenue',
      note: 'Job Note',
      notePlural: 'Job Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'Document',
      filePlural: 'Documents',
      followUp: 'Follow-up',
      consultation: 'Site Assessment',
      proposal: 'Project Estimate',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Worker',
      staffPlural: 'Workers',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Project Hub', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'opportunities', label: 'Projects', icon: 'HardHat', href: '/dashboard/opportunities', priority: 3, group: 'primary' },
      { id: 'appointments', label: 'Site Visits', icon: 'Calendar', href: '/appointments', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'teams', label: 'Team', icon: 'Users', href: '/dashboard/teams', priority: 8, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 9, group: 'tools' },
    ],
    kpis: [
      { id: 'active_projects', label: 'Active Projects', icon: 'HardHat', format: 'number', description: 'Projects in progress', query: 'active_opportunities' },
      { id: 'site_visits_week', label: 'Site Visits This Week', icon: 'Calendar', format: 'number', description: 'Scheduled site visits', query: 'viewings_this_week' },
      { id: 'pending_estimates', label: 'Pending Estimates', icon: 'FileText', format: 'number', description: 'Awaiting client approval', query: 'open_offers' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'outstanding', label: 'Outstanding Invoices', icon: 'AlertCircle', format: 'currency', description: 'Unpaid invoices', query: 'outstanding_invoices' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Project Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Business Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_visits', label: "Today's Site Visits", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Project Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_visits', label: 'Upcoming Site Visits', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'tasks', label: 'Active Tasks', type: 'list', size: 'md', priority: 6, query: 'pending_tasks' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'inquiry', label: 'New Inquiry', color: '#3b82f6', probability: 10 },
      { id: 'assessment', label: 'Site Assessment', color: '#8b5cf6', probability: 25 },
      { id: 'estimate', label: 'Estimate Sent', color: '#06b6d4', probability: 45 },
      { id: 'approved', label: 'Estimate Approved', color: '#f59e0b', probability: 65 },
      { id: 'in_progress', label: 'In Progress', color: '#f97316', probability: 80 },
      { id: 'completed', label: 'Completed', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Site Visit Confirmation', description: 'Confirm site visits when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Site Visit Confirmation', message: 'Hi {{customer_name}},\n\nThis confirms our site visit on {{appointment_date}} at {{appointment_time}}.\n\nSee you then!\n\n{{business_name}}' },
      { name: 'Post-Visit Follow-up', description: 'Follow up after site visit', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'Site Visit Follow-up & Estimate', message: 'Hi {{customer_name}},\n\nThank you for the site visit. As discussed, I\'ll prepare the estimate and send it over shortly.\n\nBest regards,\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: [],
  },

  car_dealer: {
    id: 'car_dealer',
    name: 'Automotive',
    description: 'Car dealerships and automotive sales',
    icon: 'Car',
    color: '#1d4ed8',
    terminology: {
      ...defaultTerminology,
      customer: 'Buyer',
      customerPlural: 'Buyers',
      appointment: 'Test Drive',
      appointmentPlural: 'Test Drives',
      project: 'Vehicle Sale',
      projectPlural: 'Vehicle Sales',
      invoice: 'Sales Invoice',
      invoicePlural: 'Sales Invoices',
      quote: 'Quote',
      quotePlural: 'Quotes',
      product: 'Vehicle',
      productPlural: 'Vehicles',
      deal: 'Deal',
      dealPlural: 'Deals',
      revenue: 'Revenue',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'Document',
      filePlural: 'Documents',
      followUp: 'Follow-up',
      consultation: 'Consultation',
      proposal: 'Offer',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Sales Rep',
      staffPlural: 'Sales Reps',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Sales Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Buyers', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Test Drives', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'opportunities', label: 'Sales Pipeline', icon: 'TrendingUp', href: '/dashboard/opportunities', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Sales Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'teams', label: 'Sales Team', icon: 'Users', href: '/dashboard/teams', priority: 8, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 9, group: 'tools' },
    ],
    kpis: [
      { id: 'test_drives_week', label: 'Test Drives This Week', icon: 'Calendar', format: 'number', description: 'Scheduled test drives', query: 'viewings_this_week' },
      { id: 'active_deals', label: 'Active Deals', icon: 'Car', format: 'number', description: 'Open sales deals', query: 'active_opportunities' },
      { id: 'closed_month', label: 'Sales This Month', icon: 'TrendingUp', format: 'number', description: 'Vehicles sold', query: 'closed_won_month' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Sales revenue', query: 'revenue_month' },
      { id: 'pipeline_value', label: 'Pipeline Value', icon: 'DollarSign', format: 'currency', description: 'Total pipeline value', query: 'pipeline_value' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Sales Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Sales Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_drives', label: "Today's Test Drives", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Sales Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_drives', label: 'Upcoming Test Drives', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'recent_buyers', label: 'Recent Buyers', type: 'list', size: 'md', priority: 6, query: 'recent_contacts' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'lead', label: 'New Lead', color: '#3b82f6', probability: 10 },
      { id: 'inquiry', label: 'Inquiry', color: '#8b5cf6', probability: 25 },
      { id: 'test_drive', label: 'Test Drive', color: '#06b6d4', probability: 45 },
      { id: 'negotiation', label: 'Negotiation', color: '#f59e0b', probability: 65 },
      { id: 'financing', label: 'Financing', color: '#f97316', probability: 80 },
      { id: 'won', label: 'Vehicle Sold', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost Sale', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Test Drive Confirmation', description: 'Confirm test drives when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Test Drive Confirmation', message: 'Hi {{customer_name}},\n\nYour test drive is confirmed for {{appointment_date}} at {{appointment_time}}.\n\nPlease bring your valid driver\'s license.\n\n{{business_name}}' },
      { name: 'Post-Test Drive Follow-up', description: 'Follow up after test drive', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 1440, subject: 'How was your test drive?', message: 'Hi {{customer_name}},\n\nThank you for the test drive yesterday! We hope you enjoyed the experience.\n\nDo you have any questions? We\'re here to help you find the perfect vehicle.\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: [],
  },

  teacher: {
    id: 'teacher',
    name: 'Education',
    description: 'Teachers, tutors, and educational services',
    icon: 'GraduationCap',
    color: '#7c3aed',
    terminology: {
      ...defaultTerminology,
      customer: 'Student',
      customerPlural: 'Students',
      appointment: 'Lesson',
      appointmentPlural: 'Lessons',
      project: 'Course',
      projectPlural: 'Courses',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Quote',
      quotePlural: 'Quotes',
      product: 'Course',
      productPlural: 'Courses',
      deal: 'Enrollment',
      dealPlural: 'Enrollments',
      revenue: 'Revenue',
      note: 'Progress Note',
      notePlural: 'Progress Notes',
      task: 'Assignment',
      taskPlural: 'Assignments',
      file: 'Resource',
      filePlural: 'Resources',
      followUp: 'Review Session',
      consultation: 'Trial Lesson',
      proposal: 'Course Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Tutor',
      staffPlural: 'Tutors',
      service: 'Course',
      servicePlural: 'Courses',
    },
    navItems: [
      { id: 'dashboard', label: 'Teaching Hub', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Students', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Lessons', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'tasks', label: 'Assignments', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 4, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 5, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 6, group: 'tools' },
      { id: 'teams', label: 'Tutors', icon: 'Users', href: '/dashboard/teams', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'lessons_today', label: 'Lessons Today', icon: 'Calendar', format: 'number', description: 'Lessons scheduled today', query: 'today_appointments' },
      { id: 'active_students', label: 'Active Students', icon: 'Users', format: 'number', description: 'Currently active students', query: 'total_contacts' },
      { id: 'pending_assignments', label: 'Pending Assignments', icon: 'BookOpen', format: 'number', description: 'Assignments to review', query: 'pending_tasks' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'new_enrollments', label: 'New Enrollments', icon: 'UserPlus', format: 'number', description: 'New students this month', query: 'contacts_added' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Teaching Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Teaching Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_lessons', label: "Today's Lessons", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'upcoming_lessons', label: 'Upcoming Lessons', type: 'list', size: 'lg', priority: 4, query: 'upcoming_appointments' },
      { id: 'recent_students', label: 'Recent Students', type: 'list', size: 'md', priority: 5, query: 'recent_contacts' },
      { id: 'assignments', label: 'Pending Assignments', type: 'list', size: 'md', priority: 6, query: 'pending_tasks' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'inquiry', label: 'New Inquiry', color: '#3b82f6', probability: 15 },
      { id: 'trial', label: 'Trial Lesson', color: '#8b5cf6', probability: 35 },
      { id: 'enrolled', label: 'Enrolled', color: '#06b6d4', probability: 60 },
      { id: 'active', label: 'Active Student', color: '#f59e0b', probability: 80 },
      { id: 'completed', label: 'Course Complete', color: '#22c55e', probability: 100 },
      { id: 'churned', label: 'Dropped', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Lesson Confirmation', description: 'Confirm lessons when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Lesson Confirmation', message: 'Hi {{customer_name}},\n\nYour lesson is confirmed for {{appointment_date}} at {{appointment_time}}.\n\nSee you then!\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: ['opportunities'],
  },

  photographer: {
    id: 'photographer',
    name: 'Photography',
    description: 'Photographers and visual content creators',
    icon: 'Camera',
    color: '#be185d',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Shoot',
      appointmentPlural: 'Shoots',
      project: 'Project',
      projectPlural: 'Projects',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Quote',
      quotePlural: 'Quotes',
      product: 'Package',
      productPlural: 'Packages',
      deal: 'Booking',
      dealPlural: 'Bookings',
      revenue: 'Revenue',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Deliverable',
      taskPlural: 'Deliverables',
      file: 'Gallery',
      filePlural: 'Galleries',
      followUp: 'Follow-up',
      consultation: 'Consultation',
      proposal: 'Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Assistant',
      staffPlural: 'Assistants',
      service: 'Package',
      servicePlural: 'Packages',
    },
    navItems: [
      { id: 'dashboard', label: 'Studio Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Shoots', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'opportunities', label: 'Pipeline', icon: 'TrendingUp', href: '/dashboard/opportunities', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Deliverables', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'shoots_month', label: 'Shoots This Month', icon: 'Camera', format: 'number', description: 'Photo shoots scheduled', query: 'viewings_this_week' },
      { id: 'pending_deliveries', label: 'Pending Deliveries', icon: 'Image', format: 'number', description: 'Galleries to deliver', query: 'pending_tasks' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'new_clients', label: 'New Clients', icon: 'UserPlus', format: 'number', description: 'New clients this month', query: 'contacts_added' },
      { id: 'pipeline_value', label: 'Pipeline Value', icon: 'TrendingUp', format: 'currency', description: 'Total pipeline value', query: 'pipeline_value' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Studio Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Studio Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_shoots', label: "Today's Shoots", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Booking Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_shoots', label: 'Upcoming Shoots', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'recent_clients', label: 'Recent Clients', type: 'list', size: 'md', priority: 6, query: 'recent_contacts' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'inquiry', label: 'New Inquiry', color: '#3b82f6', probability: 10 },
      { id: 'consultation', label: 'Consultation', color: '#8b5cf6', probability: 30 },
      { id: 'proposal', label: 'Proposal Sent', color: '#06b6d4', probability: 50 },
      { id: 'booked', label: 'Booked', color: '#f59e0b', probability: 75 },
      { id: 'shot', label: 'Shoot Complete', color: '#f97316', probability: 90 },
      { id: 'delivered', label: 'Gallery Delivered', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Shoot Confirmation', description: 'Confirm shoots when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Shoot Confirmation', message: 'Hi {{customer_name}},\n\nYour shoot is confirmed for {{appointment_date}} at {{appointment_time}}.\n\nLooking forward to capturing great moments!\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows'],
    hiddenModules: ['teams'],
  },

  accountant: {
    id: 'accountant',
    name: 'Accounting',
    description: 'Accountants, bookkeepers, and financial advisors',
    icon: 'Calculator',
    color: '#059669',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Consultation',
      appointmentPlural: 'Consultations',
      project: 'Engagement',
      projectPlural: 'Engagements',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Proposal',
      quotePlural: 'Proposals',
      product: 'Service',
      productPlural: 'Services',
      deal: 'Engagement',
      dealPlural: 'Engagements',
      revenue: 'Revenue',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'Document',
      filePlural: 'Documents',
      followUp: 'Follow-up',
      consultation: 'Initial Consultation',
      proposal: 'Service Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Accountant',
      staffPlural: 'Accountants',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Practice Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Consultations', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 4, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 5, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 6, group: 'tools' },
      { id: 'teams', label: 'Staff', icon: 'Users', href: '/dashboard/teams', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'consultations_week', label: 'Consultations This Week', icon: 'Calendar', format: 'number', description: 'Client consultations', query: 'viewings_this_week' },
      { id: 'active_engagements', label: 'Active Engagements', icon: 'Briefcase', format: 'number', description: 'Ongoing engagements', query: 'active_opportunities' },
      { id: 'pending_tasks', label: 'Pending Tasks', icon: 'CheckSquare', format: 'number', description: 'Tasks requiring attention', query: 'pending_tasks' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'outstanding', label: 'Outstanding Invoices', icon: 'AlertCircle', format: 'currency', description: 'Unpaid invoices', query: 'outstanding_invoices' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Practice Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Practice Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_consultations', label: "Today's Consultations", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'upcoming_consultations', label: 'Upcoming Consultations', type: 'list', size: 'md', priority: 4, query: 'upcoming_appointments' },
      { id: 'pending_tasks', label: 'Pending Tasks', type: 'list', size: 'md', priority: 5, query: 'pending_tasks' },
      { id: 'recent_clients', label: 'Recent Clients', type: 'list', size: 'md', priority: 6, query: 'recent_contacts' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'inquiry', label: 'New Inquiry', color: '#3b82f6', probability: 15 },
      { id: 'consultation', label: 'Initial Consultation', color: '#8b5cf6', probability: 30 },
      { id: 'proposal', label: 'Proposal Sent', color: '#06b6d4', probability: 50 },
      { id: 'engaged', label: 'Engagement Signed', color: '#f59e0b', probability: 75 },
      { id: 'in_progress', label: 'In Progress', color: '#f97316', probability: 90 },
      { id: 'completed', label: 'Completed', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Consultation Confirmation', description: 'Confirm consultations when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Consultation Confirmation', message: 'Hi {{customer_name}},\n\nThis confirms your consultation on {{appointment_date}} at {{appointment_time}}.\n\nPlease bring any relevant financial documents.\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: ['opportunities'],
  },

  marketing_agency: {
    id: 'marketing_agency',
    name: 'Marketing Agency',
    description: 'Marketing, advertising, and digital agencies',
    icon: 'Megaphone',
    color: '#e11d48',
    terminology: {
      ...defaultTerminology,
      customer: 'Client',
      customerPlural: 'Clients',
      appointment: 'Meeting',
      appointmentPlural: 'Meetings',
      project: 'Campaign',
      projectPlural: 'Campaigns',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Proposal',
      quotePlural: 'Proposals',
      product: 'Service',
      productPlural: 'Services',
      deal: 'Deal',
      dealPlural: 'Deals',
      revenue: 'Revenue',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Deliverable',
      taskPlural: 'Deliverables',
      file: 'Asset',
      filePlural: 'Assets',
      followUp: 'Follow-up',
      consultation: 'Strategy Session',
      proposal: 'Proposal',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Team Member',
      staffPlural: 'Team Members',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Agency Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Clients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'opportunities', label: 'Pipeline', icon: 'TrendingUp', href: '/dashboard/opportunities', priority: 3, group: 'primary' },
      { id: 'appointments', label: 'Meetings', icon: 'Calendar', href: '/appointments', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Deliverables', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'teams', label: 'Team', icon: 'Users', href: '/dashboard/teams', priority: 8, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 9, group: 'tools' },
    ],
    kpis: [
      { id: 'active_campaigns', label: 'Active Campaigns', icon: 'Megaphone', format: 'number', description: 'Running campaigns', query: 'active_opportunities' },
      { id: 'meetings_week', label: 'Meetings This Week', icon: 'Calendar', format: 'number', description: 'Client meetings', query: 'viewings_this_week' },
      { id: 'pending_proposals', label: 'Pending Proposals', icon: 'FileText', format: 'number', description: 'Awaiting response', query: 'open_offers' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'pipeline_value', label: 'Pipeline Value', icon: 'TrendingUp', format: 'currency', description: 'Total pipeline value', query: 'pipeline_value' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Agency Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Agency Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_meetings', label: "Today's Meetings", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Client Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_meetings', label: 'Upcoming Meetings', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'deliverables', label: 'Pending Deliverables', type: 'list', size: 'md', priority: 6, query: 'pending_tasks' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'lead', label: 'New Lead', color: '#3b82f6', probability: 10 },
      { id: 'discovery', label: 'Discovery Call', color: '#8b5cf6', probability: 25 },
      { id: 'proposal', label: 'Proposal Sent', color: '#06b6d4', probability: 45 },
      { id: 'negotiation', label: 'Negotiation', color: '#f59e0b', probability: 65 },
      { id: 'won', label: 'Client Won', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Meeting Confirmation', description: 'Confirm client meetings', trigger: 'booking_confirmed', actionType: 'email', subject: 'Meeting Confirmation', message: 'Hi {{customer_name}},\n\nLooking forward to our meeting on {{appointment_date}} at {{appointment_time}}.\n\nSee you then!\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: [],
  },

  veterinary: {
    id: 'veterinary',
    name: 'Veterinary',
    description: 'Veterinary clinics and animal healthcare',
    icon: 'PawPrint',
    color: '#16a34a',
    terminology: {
      ...defaultTerminology,
      customer: 'Pet Owner',
      customerPlural: 'Pet Owners',
      appointment: 'Appointment',
      appointmentPlural: 'Appointments',
      project: 'Treatment Plan',
      projectPlural: 'Treatment Plans',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Estimate',
      quotePlural: 'Estimates',
      product: 'Product',
      productPlural: 'Products',
      deal: 'Case',
      dealPlural: 'Cases',
      revenue: 'Revenue',
      note: 'Clinical Note',
      notePlural: 'Clinical Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'Record',
      filePlural: 'Records',
      followUp: 'Follow-up Visit',
      consultation: 'Consultation',
      proposal: 'Treatment Estimate',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Veterinarian',
      staffPlural: 'Veterinarians',
      service: 'Service',
      servicePlural: 'Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Clinic Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Pet Owners', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Appointments', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 4, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 5, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 6, group: 'tools' },
      { id: 'teams', label: 'Veterinarians', icon: 'Users', href: '/dashboard/teams', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'appointments_today', label: 'Appointments Today', icon: 'Calendar', format: 'number', description: 'Appointments today', query: 'today_appointments' },
      { id: 'pending_followups', label: 'Pending Follow-ups', icon: 'Clock', format: 'number', description: 'Follow-up visits needed', query: 'pending_followups' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'total_patients', label: 'Total Patients', icon: 'PawPrint', format: 'number', description: 'Unique patients', query: 'total_contacts' },
      { id: 'no_shows', label: 'No-shows', icon: 'UserX', format: 'number', description: 'Missed appointments', query: 'no_shows_month' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Clinic Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Clinic Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_appointments', label: "Today's Appointments", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'upcoming_appointments', label: 'Upcoming Appointments', type: 'list', size: 'lg', priority: 4, query: 'upcoming_appointments' },
      { id: 'recent_patients', label: 'Recent Patients', type: 'list', size: 'md', priority: 5, query: 'recent_contacts' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 6, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 7, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'new_patient', label: 'New Patient', color: '#3b82f6', probability: 20 },
      { id: 'first_visit', label: 'First Visit', color: '#8b5cf6', probability: 40 },
      { id: 'treatment', label: 'In Treatment', color: '#f59e0b', probability: 65 },
      { id: 'follow_up', label: 'Follow-up Required', color: '#f97316', probability: 80 },
      { id: 'completed', label: 'Treatment Complete', color: '#22c55e', probability: 100 },
    ],
    defaultWorkflows: [
      { name: 'Appointment Confirmation', description: 'Confirm appointments when booked', trigger: 'booking_confirmed', actionType: 'email', subject: 'Appointment Confirmation', message: 'Hi {{customer_name}},\n\nThis confirms your appointment on {{appointment_date}} at {{appointment_time}}.\n\nPlease bring your pet\'s vaccination records.\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: ['opportunities'],
  },

  dentist: {
    id: 'dentist',
    name: 'Dental',
    description: 'Dental clinics and dental practices',
    icon: 'Smile',
    color: '#0ea5e9',
    terminology: {
      ...defaultTerminology,
      customer: 'Patient',
      customerPlural: 'Patients',
      appointment: 'Appointment',
      appointmentPlural: 'Appointments',
      project: 'Treatment Plan',
      projectPlural: 'Treatment Plans',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Treatment Estimate',
      quotePlural: 'Treatment Estimates',
      product: 'Service',
      productPlural: 'Services',
      deal: 'Case',
      dealPlural: 'Cases',
      revenue: 'Revenue',
      note: 'Clinical Note',
      notePlural: 'Clinical Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'Record',
      filePlural: 'Records',
      followUp: 'Recall Visit',
      consultation: 'Consultation',
      proposal: 'Treatment Plan',
      payment: 'Payment',
      paymentPlural: 'Payments',
      staff: 'Dentist',
      staffPlural: 'Dentists',
      service: 'Dental Service',
      servicePlural: 'Dental Services',
    },
    navItems: [
      { id: 'dashboard', label: 'Practice Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Patients', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'appointments', label: 'Appointments', icon: 'Calendar', href: '/appointments', priority: 3, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 4, group: 'secondary' },
      { id: 'invoices', label: 'Invoices', icon: 'DollarSign', href: '/dashboard/invoices', priority: 5, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 6, group: 'tools' },
      { id: 'teams', label: 'Dentists', icon: 'Users', href: '/dashboard/teams', priority: 7, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 8, group: 'tools' },
    ],
    kpis: [
      { id: 'appointments_today', label: 'Appointments Today', icon: 'Calendar', format: 'number', description: 'Appointments today', query: 'today_appointments' },
      { id: 'recall_due', label: 'Recall Due', icon: 'Clock', format: 'number', description: 'Patients due for recall', query: 'pending_followups' },
      { id: 'revenue_month', label: 'Monthly Revenue', icon: 'DollarSign', format: 'currency', description: 'Revenue this month', query: 'revenue_month' },
      { id: 'total_patients', label: 'Total Patients', icon: 'Users', format: 'number', description: 'Active patient base', query: 'total_contacts' },
      { id: 'no_shows', label: 'No-shows', icon: 'UserX', format: 'number', description: 'Missed appointments', query: 'no_shows_month' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Practice Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Practice Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_appointments', label: "Today's Appointments", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'upcoming_appointments', label: 'Upcoming Appointments', type: 'list', size: 'lg', priority: 4, query: 'upcoming_appointments' },
      { id: 'recent_patients', label: 'Recent Patients', type: 'list', size: 'md', priority: 5, query: 'recent_contacts' },
      { id: 'recall_list', label: 'Recall List', type: 'list', size: 'md', priority: 6, query: 'pending_followups' },
      { id: 'revenue', label: 'Revenue Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'new_patient', label: 'New Patient', color: '#3b82f6', probability: 20 },
      { id: 'initial_exam', label: 'Initial Exam', color: '#8b5cf6', probability: 40 },
      { id: 'treatment_plan', label: 'Treatment Planned', color: '#06b6d4', probability: 60 },
      { id: 'in_treatment', label: 'In Treatment', color: '#f59e0b', probability: 75 },
      { id: 'completed', label: 'Treatment Complete', color: '#22c55e', probability: 100 },
    ],
    defaultWorkflows: [
      { name: 'Appointment Confirmation', description: 'Confirm dental appointments', trigger: 'booking_confirmed', actionType: 'email', subject: 'Dental Appointment Confirmation', message: 'Hi {{customer_name}},\n\nYour dental appointment is confirmed for {{appointment_date}} at {{appointment_time}}.\n\n{{business_name}}' },
      { name: 'Recall Reminder', description: 'Remind patients for recall visits', trigger: 'appointment_completed', actionType: 'email', triggerMinutes: 40320, subject: 'Time for your dental check-up!', message: 'Hi {{customer_name}},\n\nIt\'s been a while since your last visit. We recommend a regular check-up.\n\nPlease call us to schedule your next appointment.\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: ['opportunities'],
  },

  insurance_agent: {
    id: 'insurance_agent',
    name: 'Insurance',
    description: 'Insurance agents and brokers',
    icon: 'Shield',
    color: '#4338ca',
    terminology: {
      ...defaultTerminology,
      customer: 'Policyholder',
      customerPlural: 'Policyholders',
      appointment: 'Consultation',
      appointmentPlural: 'Consultations',
      project: 'Policy',
      projectPlural: 'Policies',
      invoice: 'Invoice',
      invoicePlural: 'Invoices',
      quote: 'Quote',
      quotePlural: 'Quotes',
      product: 'Insurance Product',
      productPlural: 'Insurance Products',
      deal: 'Policy',
      dealPlural: 'Policies',
      revenue: 'Premium Revenue',
      note: 'Note',
      notePlural: 'Notes',
      task: 'Task',
      taskPlural: 'Tasks',
      file: 'Document',
      filePlural: 'Documents',
      followUp: 'Follow-up',
      consultation: 'Insurance Consultation',
      proposal: 'Coverage Proposal',
      payment: 'Premium',
      paymentPlural: 'Premiums',
      staff: 'Agent',
      staffPlural: 'Agents',
      service: 'Insurance Plan',
      servicePlural: 'Insurance Plans',
    },
    navItems: [
      { id: 'dashboard', label: 'Agency Dashboard', icon: 'LayoutDashboard', href: '/dashboard', priority: 1, group: 'primary' },
      { id: 'contacts', label: 'Policyholders', icon: 'Users', href: '/dashboard/contacts', priority: 2, group: 'primary' },
      { id: 'opportunities', label: 'Pipeline', icon: 'TrendingUp', href: '/dashboard/opportunities', priority: 3, group: 'primary' },
      { id: 'appointments', label: 'Consultations', icon: 'Calendar', href: '/appointments', priority: 4, group: 'primary' },
      { id: 'tasks', label: 'Tasks', icon: 'CheckSquare', href: '/dashboard/tasks', priority: 5, group: 'secondary' },
      { id: 'invoices', label: 'Premiums', icon: 'DollarSign', href: '/dashboard/invoices', priority: 6, group: 'secondary' },
      { id: 'workflows', label: 'Automations', icon: 'Zap', href: '/dashboard/workflows', priority: 7, group: 'tools' },
      { id: 'teams', label: 'Agents', icon: 'Users', href: '/dashboard/teams', priority: 8, group: 'tools' },
      { id: 'settings', label: 'Settings', icon: 'Settings', href: '/settings', priority: 9, group: 'tools' },
    ],
    kpis: [
      { id: 'active_policies', label: 'Active Policies', icon: 'Shield', format: 'number', description: 'Active insurance policies', query: 'active_opportunities' },
      { id: 'consultations_week', label: 'Consultations This Week', icon: 'Calendar', format: 'number', description: 'Scheduled consultations', query: 'viewings_this_week' },
      { id: 'pending_quotes', label: 'Pending Quotes', icon: 'FileText', format: 'number', description: 'Awaiting client decision', query: 'open_offers' },
      { id: 'premiums_month', label: 'Premiums This Month', icon: 'DollarSign', format: 'currency', description: 'Premium revenue collected', query: 'revenue_month' },
      { id: 'pipeline_value', label: 'Pipeline Value', icon: 'TrendingUp', format: 'currency', description: 'Total pipeline value', query: 'pipeline_value' },
    ],
    dashboardWidgets: [
      { id: 'ai_assistant', label: 'AI Insurance Assistant', type: 'ai', size: 'full', priority: 1, query: 'ai_insights' },
      { id: 'stats', label: 'Agency Overview', type: 'stat', size: 'full', priority: 2, query: 'stats' },
      { id: 'today_consultations', label: "Today's Consultations", type: 'list', size: 'lg', priority: 3, query: 'today_appointments' },
      { id: 'pipeline', label: 'Policy Pipeline', type: 'pipeline', size: 'lg', priority: 4, query: 'pipeline' },
      { id: 'upcoming_consultations', label: 'Upcoming Consultations', type: 'list', size: 'md', priority: 5, query: 'upcoming_appointments' },
      { id: 'recent_policyholders', label: 'Recent Policyholders', type: 'list', size: 'md', priority: 6, query: 'recent_contacts' },
      { id: 'revenue', label: 'Premium Overview', type: 'revenue', size: 'md', priority: 7, query: 'revenue' },
      { id: 'quick_actions', label: 'Quick Actions', type: 'quick-actions', size: 'sm', priority: 8, query: 'quick_actions' },
    ],
    pipelineStages: [
      { id: 'lead', label: 'New Lead', color: '#3b82f6', probability: 10 },
      { id: 'consultation', label: 'Consultation', color: '#8b5cf6', probability: 30 },
      { id: 'quote', label: 'Quote Sent', color: '#06b6d4', probability: 50 },
      { id: 'negotiation', label: 'Negotiation', color: '#f59e0b', probability: 70 },
      { id: 'won', label: 'Policy Sold', color: '#22c55e', probability: 100 },
      { id: 'lost', label: 'Lost', color: '#ef4444', probability: 0 },
    ],
    defaultWorkflows: [
      { name: 'Consultation Confirmation', description: 'Confirm insurance consultations', trigger: 'booking_confirmed', actionType: 'email', subject: 'Consultation Confirmation', message: 'Hi {{customer_name}},\n\nThis confirms your insurance consultation on {{appointment_date}} at {{appointment_time}}.\n\nPlease bring any existing policy documents.\n\n{{business_name}}' },
    ],
    enabledModules: ['contacts', 'appointments', 'opportunities', 'tasks', 'invoices', 'workflows', 'teams'],
    hiddenModules: [],
  },
}

export function getProfessionConfig(professionId: ProfessionId): ProfessionConfig {
  return professionConfigs[professionId] || professionConfigs.freelancer
}

export function getTerminology(professionId: ProfessionId): ProfessionTerminology {
  return getProfessionConfig(professionId).terminology
}

export function getNavItems(professionId: ProfessionId): NavItem[] {
  return getProfessionConfig(professionId).navItems.sort((a, b) => a.priority - b.priority)
}

export function getKPIs(professionId: ProfessionId): KPIDefinition[] {
  return getProfessionConfig(professionId).kpis
}

export function getDashboardWidgets(professionId: ProfessionId): DashboardWidget[] {
  return getProfessionConfig(professionId).dashboardWidgets.sort((a, b) => a.priority - b.priority)
}

export function getPipelineStages(professionId: ProfessionId): PipelineStage[] {
  return getProfessionConfig(professionId).pipelineStages
}

export function getDefaultWorkflows(professionId: ProfessionId): DefaultWorkflow[] {
  return getProfessionConfig(professionId).defaultWorkflows
}

export function getAllProfessions(): Array<{ id: ProfessionId; name: string; description: string; icon: string; color: string }> {
  return Object.values(professionConfigs).map(p => ({
    id: p.id,
    name: p.name,
    description: p.description,
    icon: p.icon,
    color: p.color,
  }))
}

export function getEnabledModules(professionId: ProfessionId): string[] {
  return getProfessionConfig(professionId).enabledModules
}

export function getHiddenModules(professionId: ProfessionId): string[] {
  return getProfessionConfig(professionId).hiddenModules
}

export function isModuleEnabled(professionId: ProfessionId, moduleId: string): boolean {
  const config = getProfessionConfig(professionId)
  return config.enabledModules.includes(moduleId) && !config.hiddenModules.includes(moduleId)
}

export function getTerminologyLabel(professionId: ProfessionId, key: keyof ProfessionTerminology): string {
  const terms = getTerminology(professionId)
  return terms[key] || defaultTerminology[key] || key
}

export function getPluralLabel(professionId: ProfessionId, key: keyof ProfessionTerminology): string {
  const terms = getTerminology(professionId)
  const pluralKey = (key + 'Plural') as keyof ProfessionTerminology
  return terms[pluralKey] || terms[key] || key
}

export type { ProfessionId, ProfessionConfig, ProfessionTerminology, NavItem, KPIDefinition, DashboardWidget, PipelineStage, DefaultWorkflow }
